# NumPy Fundamentals

## Author: Sonia Tana

This exercise practices creating and working with NumPy arrays in Python.

In [1]:
import numpy as np

In [2]:
No module named numpy

SyntaxError: invalid syntax (2002943307.py, line 1)

## Array Basics

In [3]:
fruits = ["apple", "banana", "cherry", "date"]

print(fruits)

['apple', 'banana', 'cherry', 'date']


In [4]:
arr_1 = np.array(fruits)

print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [5]:
print(arr_1.dtype)
# The dtype returned is a Unicode string type.
# The number represents the maximum length of the strings.

<U6


In [6]:
arr_2 = np.array([
    [10, 11, 12],
    [13, 14, 15]
])

print(arr_2)

[[10 11 12]
 [13 14 15]]


In [7]:
print(arr_2.T)
# No, using .T does not permanently change arr_2.
# It only displays a transposed version of the array.

[[10 13]
 [11 14]
 [12 15]]


In [8]:
arr_3 = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

print(arr_3)

[[1 3 5]
 [2 4 6]]


In [9]:
arr_4 = np.array([
    arr_3[0, 2],
    arr_3[1, 1]
])

print(arr_4)

[5 4]


In [10]:
arr_5 = np.ones((2, 2, 2))

print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
