# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [3]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [4]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


first loop goes through each row in the array and multiplies the entire row by 2. The second loop goes through each individual value inside the rows and multiplies each number by 2 separately.

In [5]:
for x in arrA:
    loop_result = x * 2
    print(loop_result)
 # This is different because the result is being stored in a variable before printing.

[22 24 26]
[28 30 32]


## Joining and Stacking Arrays

In [6]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [7]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [9]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))

print(stacked_array_1)
# np.stack combines arrays into a new dimension.


[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [10]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)

print(another_2)
# The error happens because the arrays do not have the same number of rows.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [11]:
vertical_stack = np.vstack((arrA, arrA))
print(vertical_stack)
# vstack joins arrays vertically (top and bottom)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [12]:
depth_stack = np.dstack((arrA, arrA))

## Splitting Arrays

In [13]:
splitsky = np.array_split(joined_array_1, 2)

print(splitsky)

# The array was split into 2 arrays.
# Each split array still has 2 dimensions

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [14]:
spliterino = np.array_split(joined_array_1, 3)

print(spliterino)

# The array was split into 3 arrays.
# Each split array still has 2 dimensions

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [15]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')

print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [17]:
arrB = np.array([
    [7, 6],
    [13, 5],
    [7, 3]
])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [18]:
print(arrB)

z = arrB < 7

arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [19]:
y = arrB >= 7

arrD = arrB[y]

print(arrD)

[ 7 13  7]
