# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

[5 2]


In [3]:
r_2 = np.random.randint(1, 21, size=(11, 2))
print(r_2)

[[ 8 20]
 [14  6]
 [15 10]
 [ 2  8]
 [10 15]
 [17  2]
 [14  1]
 [14  9]
 [ 8 13]
 [13 19]
 [ 8  1]]


In [4]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.21545729]
 [0.26937653]]


In [5]:
r_4 = np.random.randint(20, 101, size=(4, 5))

print(r_4)

[[76 41 44 56 80]
 [53 53 47 43 25]
 [43 91 26 30 73]
 [68 76 93 29 64]]


In [6]:
r_5 = np.random.rand(4, 5)

print(r_5)

[[0.28146197 0.17382093 0.94961022 0.94800363 0.63008514]
 [0.29815208 0.25752084 0.79400026 0.37386075 0.68256763]
 [0.73656087 0.55374189 0.36929113 0.78883608 0.09392543]
 [0.41304903 0.85817633 0.44366789 0.27177675 0.49072035]]


## Generating Random Choices from an Array

In [7]:
students = np.array([
    "Sonia",
    "Alex",
    "Maria",
    "John",
    "Sarah",
    "David",
    "Linda",
    "Chris",
    "James",
    "Sophia",
    "Daniel",
    "Emma"
])

In [8]:
call_on = np.random.choice(students)

print(call_on)

Alex


In [9]:
breakout_groups = np.random.choice(students, size=(3, 4))

print(breakout_groups)
# This may not be the best way to assign groups because some students could appear more than once while others may not appear at all.

[['Emma' 'Sonia' 'Emma' 'Sarah']
 ['Sophia' 'Sophia' 'Emma' 'John']
 ['Emma' 'Sonia' 'Sarah' 'Sonia']]


In [10]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.30, 0.10, 0.10, 0.10, 0.10, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.00]
)

print(call_on_weighted)

# Sonia has a 30% chance of being selected.
# Emma has a 0% chance of being selected.
# The other students share the remaining probabilities

['Sophia' 'Sonia' 'John' 'Sophia' 'Alex']


## Generating a Normal Distribution

In [11]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))

print(bell_curve)

[[14.70265589  2.54463633  8.35644092 14.4274358   8.19374343]
 [ 7.93043781 18.28273424  7.47755178 13.8841233  10.04142549]
 [ 4.95884965 16.46267248  5.79859847  8.32008598  4.03107585]
 [ 8.51271495  9.03322726 11.8044336   6.1992988  15.66264899]]
