# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np 

## Sample Arrays

In [2]:
r_1 = np.random.randint(1, 21, size=2)

r_2 = np.random.randint(1, 21, size=(1, 2))

r_3 = np.random.rand(2, 1)

r_4 = np.random.randint(20, 101, size=(4, 5))

r_5 = np.random.rand(4, 5)

print(r_1)
print(r_2)
print(r_3)
print(r_4)
print(r_5)

[ 2 12]
[[15  2]]
[[0.8453022 ]
 [0.13077512]]
[[33 40 89 67 46]
 [21 33 33 39 69]
 [55 67 49 76 94]
 [73 55 92 42 31]]
[[0.30907794 0.88707497 0.83232043 0.26774596 0.37183197]
 [0.30133656 0.90481049 0.22707764 0.0657923  0.64062676]
 [0.19046716 0.84623901 0.16267234 0.27659444 0.81329753]
 [0.40487852 0.37522408 0.0570126  0.98408649 0.81750697]]


## Permutations

In [4]:
print(r_4)

[[33 40 89 67 46]
 [21 33 33 39 69]
 [55 67 49 76 94]
 [73 55 92 42 31]]


In [5]:
np.random.shuffle(r_4)

print(r_4)

[[55 67 49 76 94]
 [21 33 33 39 69]
 [73 55 92 42 31]
 [33 40 89 67 46]]


The shuffle function rearranged the rows in the array. The values inside each row stayed together, but the order of the rows changed.

## Mathematical Operations

In [6]:
print(r_1)
print(r_1.shape)

print(r_2)
print(r_2.shape)

result_1 = np.add(r_1, r_2)

print(result_1)
print(result_1.shape)

[ 2 12]
(2,)
[[15  2]]
(1, 2)
[[17 14]]
(1, 2)


In [7]:
print(r_1)
print(r_1.shape)

print(r_3)
print(r_3.shape)

result_2 = np.add(r_1, r_3)

print(result_2)
print(result_2.shape)

[ 2 12]
(2,)
[[0.8453022 ]
 [0.13077512]]
(2, 1)
[[ 2.8453022  12.8453022 ]
 [ 2.13077512 12.13077512]]
(2, 2)


In [8]:
print(r_2)
print(r_2.shape)

print(r_4)
print(r_4.shape)

result_3 = np.add(r_2, r_4)

print(result_3)
print(result_3.shape)

# This error happens because the arrays have incompatible shapes.
# r_2 has shape (1,2) while r_4 has shape (4,5),
# so NumPy cannot broadcast them together.

[[15  2]]
(1, 2)
[[55 67 49 76 94]
 [21 33 33 39 69]
 [73 55 92 42 31]
 [33 40 89 67 46]]
(4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [9]:
np.add(r_1, r_4)
# r_1 and r_4 cannot be added because their shapes are incompatible for broadcasting.

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [10]:
print(r_4)

print(np.add(np.array([1]), r_4))

[[55 67 49 76 94]
 [21 33 33 39 69]
 [73 55 92 42 31]
 [33 40 89 67 46]]
[[56 68 50 77 95]
 [22 34 34 40 70]
 [74 56 93 43 32]
 [34 41 90 68 47]]


In [11]:
print(np.add(np.array([[1]]), r_4))

[[56 68 50 77 95]
 [22 34 34 40 70]
 [74 56 93 43 32]
 [34 41 90 68 47]]


In [12]:
print(np.add(np.array([[1]]), r_4))

[[56 68 50 77 95]
 [22 34 34 40 70]
 [74 56 93 43 32]
 [34 41 90 68 47]]


In [13]:
print(np.add(np.array([[1],[1]]), r_4))
# This error happens because the shapes do not align correctly for broadcasting.

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Broadcasting allows NumPy to perform operations on arrays with different shapes when their dimensions are compatible. Smaller arrays are expanded to match larger arrays. The resulting shape depends on how the dimensions align during the operation.

## Rounding

In [15]:
print(r_3)

[[0.8453022 ]
 [0.13077512]]


In [16]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [17]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [18]:
print(np.ceil(r_3))

[[1.]
 [1.]]


In [19]:
print(np.round(r_3, 2))

[[0.85]
 [0.13]]


## Cumulative Operations

In [20]:
print(r_4)

[[55 67 49 76 94]
 [21 33 33 39 69]
 [73 55 92 42 31]
 [33 40 89 67 46]]


In [21]:
print(np.sum(r_4))

1104


In [22]:
print(np.sum(r_4, axis=0))

[182 195 263 224 240]


In [23]:
print(np.sum(r_4, axis=1))

[341 195 293 275]


In [24]:
print(np.cumsum(r_4))

[  55  122  171  247  341  362  395  428  467  536  609  664  756  798
  829  862  902  991 1058 1104]


In [25]:
print(np.cumsum(r_4, axis=0))

[[ 55  67  49  76  94]
 [ 76 100  82 115 163]
 [149 155 174 157 194]
 [182 195 263 224 240]]


## Grocery Problem

In [26]:
bag1 = np.array([2, 3, 4, 0])

bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [27]:
bag1_total = np.sum(bag1)
bag2_total = np.sum(bag2)

print(f"The first bag contains {bag1_total} items, and the second bag contains {bag2_total} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [ ]:
category_totals = np.add(bag1, bag2)

print(category_totals)

print(f"There are {category_totals[0]} vegetables, {category_totals[1]} fruits, {category_totals[2]} boxes of snacks, and {category_totals[3]} beverages.")

## Teamwork

In [28]:
ali = np.array([5, 4, 6, 4, 2])

print(ali)

[5 4 6 4 2]


In [29]:
ben = np.array([0, 5, 5, 3, 4])

print(ben)

[0 5 5 3 4]


In [30]:
carla = np.array([3, 6, 0, 3, 4])

print(carla)

[3 6 0 3 4]


In [31]:
all_knocks = np.array([ali, ben, carla])

print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [32]:
person_totals = np.sum(all_knocks, axis=1)

group_total = np.sum(all_knocks)

print(person_totals)

print(group_total)

[21 17 16]
54


In [33]:
daily_totals = np.sum(all_knocks, axis=0)

rolling_total = np.cumsum(daily_totals)

estimated_votes = rolling_total / 2

print(estimated_votes)

[ 4.  11.5 17.  22.  27. ]
